import markdown
import os

# Path to the markdown file (in the artifacts directory)
MD_FILE = "/Users/aditya/.gemini/antigravity/brain/ae347a94-a2f2-43e1-84da-d8424e6d9e2b/EVOLUTION_AND_GUIDE.md"
HTML_FILE = "Darknet_Mirror_Detection_Whitepaper.html"

# CSS for a professional "Whitepaper" look
CSS = """
<style>
    body {
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
        line-height: 1.6;
        color: #333;
        max_width: 800px;
        margin: 0 auto;
        padding: 40px;
        background-color: #fff;
    }
    h1 {
        color: #2c3e50;
        border-bottom: 2px solid #2c3e50;
        padding-bottom: 10px;
        margin-top: 40px;
    }
    h2 {
        color: #34495e;
        margin-top: 30px;
        border-bottom: 1px solid #eee;
        padding-bottom: 5px;
    }
    h3 {
        color: #7f8c8d;
        margin-top: 25px;
    }
    code {
        background-color: #f8f9fa;
        padding: 2px 5px;
        border-radius: 3px;
        font-family: 'Monaco', 'Consolas', monospace;
        color: #e74c3c;
    }
    pre {
        background-color: #f8f9fa;
        padding: 15px;
        border-radius: 5px;
        border: 1px solid #e1e4e8;
        overflow-x: auto;
    }
    pre code {
        background-color: transparent;
        padding: 0;
        color: #333;
    }
    blockquote {
        border-left: 4px solid #3498db;
        margin: 0;
        padding-left: 20px;
        color: #555;
        background-color: #f1f9ff;
        padding: 10px 20px;
    }
    table {
        width: 100%;
        border-collapse: collapse;
        margin: 20px 0;
    }
    th, td {
        border: 1px solid #ddd;
        padding: 12px;
        text-align: left;
    }
    th {
        background-color: #f2f2f2;
        color: #333;
    }
    tr:nth-child(even) {
        background-color: #f9f9f9;
    }
    .footer {
        margin-top: 50px;
        text-align: center;
        font-size: 0.8em;
        color: #999;
        border-top: 1px solid #eee;
        padding-top: 20px;
    }
</style>
"""

def convert_to_html():
    try:
        if not os.path.exists(MD_FILE):
            print(f"Error: Could not find markdown file at {MD_FILE}")
            return

        with open(MD_FILE, "r", encoding="utf-8") as f:
            text = f.read()

        html_content = markdown.markdown(text, extensions=['tables', 'fenced_code'])

        final_html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>Darknet Mirror Detection Whitepaper</title>
            {CSS}
        </head>
        <body>
            {html_content}
            <div class="footer">Generated by Darknet Mirror Detection System v2.0</div>
        </body>
        </html>
        """

        with open(HTML_FILE, "w", encoding="utf-8") as f:
            f.write(final_html)
            
        print(f"✅ Successfully created {HTML_FILE}")
        print(f"📍 Location: {os.path.abspath(HTML_FILE)}")

    except Exception as e:
        print(f"Conversion failed: {e}")

if __name__ == "__main__":
    convert_to_html()
